#! /usr/bin/env python
# encoding: utf-8
# Thomas Nagy, 2006-2010 (ita)

# the following two variables are used by the target "waf dist"
import sys
sys.path.insert(0, './waf_tools')

VERSION = '0.0.1'
APPNAME = 'cxx_test'

# these variables are mandatory ('/' are converted automatically)
top = '.'
out = 'build'


def options(opt):
    opt.load('compiler_cxx')


def configure(conf):
    conf.load('compiler_cxx')


def build(bld):
    bld.shlib(source='im2col.cpp', target='im2col')
